sonar.projectKey=ANRROUS_clinica-x
sonar.organization=anrrous
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/__pycache__/**,**/generated/**,**/*.pyc,**/coverage/**
